[general]
import = ["~/.config/alacritty/theme.toml"]

[window]
padding = { x = 10, y = 10 }
opacity = 1.0

[font]
size = 12.0

[font.normal]
family = "Iosevka"
style = "Regular Extended"

[font.bold]
family = "Iosevka"
style = "Bold Extended"

[font.italic]
family = "Iosevka"
style = "Regular Extended Oblique"

[font.bold_italic]
family = "Iosevka"
style = "Bold Extended Oblique"

[cursor]
style = "Block"
