# Lazygit configuration
# Git UI for terminal

gui:
  # Window settings
  screenMode: "normal"
  scrollHeight: 2
  scrollPastBottom: true
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  showRandomTip: true
  showCommandLog: true
  commandLogSize: 8
  splitDirection: "auto"
  language: "en"
  # Colors (Catppuccin Mocha theme)
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#45475a"
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
git:
  # Git settings
  pagers:
    - colorArg: always
      pager: "less -RFX"
  commit:
    signOff: false
  autoFetch: true
  autoRefresh: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=short --pretty=medium {{branchName}} --"
  overrideGpg: false
  disableForcePushing: false
  parseEmoji: false
  allBranchesLogCmds:
    - git log --graph --color=always --abbrev-commit --decorate --date=short --pretty=medium --all
keybinding:
  universal:
    quit: "q"
    quit-alt1: "<c-c>"
    return: "<enter>"
    quitWithoutChangingDirectory: "Q"
    togglePanel: "<tab>"
    prevItem: "<up>"
    nextItem: "<down>"
    prevItemAlt: "k"
    nextItemAlt: "j"
    prevPage: "<c-u>"
    nextPage: "<c-d>"
    scrollLeft: "h"
    scrollRight: "l"
    gotoTop: "g"
    gotoBottom: "G"
    toggleRangeSelect: "v"
    rangeSelectDown: "<s-down>"
    rangeSelectUp: "<s-up>"
    startSearch: "/"
    optionMenuAlt: "?"
    toggleWhitespaceInDiffView: "<c-w>"
    increaseRenamePanelSize: "]"
    decreaseRenamePanelSize: "["
    openRecentReposMenu: "<c-r>"
  status:
    checkForUpdate: "u"
    recentRepos: "<enter>"
  files:
    commitChanges: "c"
    commitChangesWithoutHook: "w"
    amendLastCommit: "A"
    commitChangesWithEditor: "C"
    ignoreFile: "d"
    refreshFiles: "r"
    stashAllChanges: "s"
    viewStashOptions: "S"
    toggleStagedAll: "a"
    viewResetOptions: "D"
    fetch: "f"
    toggleTreeView: "`"
    openMergeOptions: "M"
    openStatusFilter: "<c-b>"
  branches:
    createPullRequest: "o"
    viewPullRequestOptions: "O"
    copyPullRequestURL: "<c-y>"
    checkout: "<enter>"
    trackRemote: "t"
    delete: "d"
    push: "p"
    pull: "u"
    rebase: "r"
    mergeIntoCurrentBranch: "M"
    viewGitFlowOptions: "i"
    fastForward: "f"
    createTag: "c"
    pushTag: "P"
    setUpstream: "u"
    fetchRemote: "f"
  commits:
    squashDown: "s"
    renameCommit: "r"
    renameCommitWithEditor: "R"
    viewResetOptions: "g"
    markCommitAsFixup: "f"
    createFixupCommit: "F"
    squashAboveCommits: "S"
    moveDownCommit: "<c-j>"
    moveUpCommit: "<c-k>"
    amendToCommit: "A"
    pickCommit: "p"
    revertCommit: "t"
    cherryPickCopy: "c"
    cherryPickCopyRange: "C"
    pasteCommits: "v"
    tagCommit: "T"
    checkoutCommit: "<enter>"
    resetCherryPick: "<c-R>"
    copyCommitMessageToClipboard: "<c-y>"
    openLogMenu: "<c-l>"
    viewBisectOptions: "b"
  stash:
    popStash: "g"
    renameStash: "r"
    deleteStash: "d"
  commitMessage:
    commitAndClose: "<enter>"
    addNewLine: "<c-o>"
customCommands:
  - key: "C"
    command: "git cz c"
    description: "Commit with commitizen"
    context: "files"
    output: terminal
