theme = "catppuccin_mocha_transparent"
# theme = "onelight"
# theme = "solarized_light"
# theme = "github_light"
# theme = "onedark"
# theme = "github_dark"
# theme = "adwaita-dark"

[editor]
line-number = "relative"
auto-save = true
auto-format = false
end-of-line-diagnostics = "hint"
# true-color = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
# display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"
nbsp = "all"

[keys.normal]
C-s = ":update"
C-p = "file_picker"
A-z = ":toggle soft-wrap.enable"
A-q = ":reflow"
F5 = ":reload"

C-h = "jump_view_left"
C-l = "jump_view_right"
C-k = "jump_view_up"
C-j = "jump_view_down"

[keys.normal.space]
"," = "buffer_picker"

[keys.normal.space.f]
f = "file_picker"
s = "global_search"
n = ":new"
g = "changed_file_picker"

[keys.normal.space.s]
w = "global_search"

[keys.normal.space.l]
g = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
]

[keys.insert]
j = { k = "normal_mode" }

[keys.normal."'"]
f = ":format"
i = ":toggle lsp.display-inlay-hints"

[keys.normal.Z]
Z = ":write-quit-all"
