---
copr_repos:
  - alternateved/ghostty
  - che/nerd-fonts
  - peterwu/iosevka
  - dejan/lazygit
  - yalter/niri
  - grahamwhiteuk/libfprint-tod
  - varlad/yazi
  - wezfurlong/wezterm-nightly
  - atim/lazydocker
  - solopasha/hyprland
  - peterwu/rendezvous
  - yorickpeterse/stylua


dnf_packages:
  # system.txt
  - ImageMagick
  - dnf-plugins-core
  - chezmoi
  - lsd
  - bluez
  - bluez-tools
  - openssh
  - feh
  - curl
  - ffmpeg
  - iputils
  - fish
  - lm_sensors
  - xdg-utils
  - xdg-user-dirs
  - power-profiles-daemon
  - rclone
  - pavucontrol
  - gnome-keyring
  - polkit
  - wev
  - nwg-look
  - qt5ct
  - qt6ct
  - udiskie
  - inxi
  - plocate
  - fcitx5
  - fcitx5-gtk
  - fcitx5-qt
  - yaru-icon-theme
  - gnome-themes-extra
  - network-manager-applet
  - NetworkManager
  - nm-connection-editor
  - fprintd
  - fprintd-pam
  - libfprint-tod
  - libfprint-2-tod1-broadcom
  - libcamera-tools
  - pipewire-plugin-libcamera
  - akmod-intel-ipu6
  - v4l2-relayd
  - tailscale

  
  # desktop.txt
  - chromium
  - flatpak
  - nautilus
  - gvfs
  - ffmpegthumbnailer
  - gnome-control-center
  - zathura
  - switcheroo-control

  - zip
  - xz
  - unzip
  - 7zip
  - cava
  - cmatrix
  - xsensors
  - crystal-dock
  - bibata-cursor-themes

  # development.txt
  - python
  - python3-pip
  - python-virtualenv
  - gh
  - rust
  - cargo
  - go
  - gcc
  - make
  - cmake
  - pkgconf
  - shellcheck
  - shfmt
  - stylua
  - strace
  - ltrace
  - lsof
  - docker
  - docker-compose
  - kubernetes-client
  - terraform
  - httpie
  - neovim
  - helix
  - bat
  - fzf
  - ripgrep
  - zoxide
  - fd-find
  - btop
  - fastfetch
  - ranger
  - tmux
  - lazygit
  - yazi
  - windsurf
  - git-delta
  - tealdeer
  - tokei
  - navi
  - direnv
  - duf

  # fonts.txt
  - jetbrains-mono-fonts
  - iosevka-fonts
  - fira-code-fonts
  - nerd-fonts
  - fontawesome-6-free-fonts
  - fontawesome-6-brands-fonts
  - google-noto-emoji-color-fonts
  - rsms-inter-fonts
  - google-noto-sans-fonts
  - google-noto-serif-fonts

  # gaming.txt
  - steam
  - gamemode
  - mangohud
  - gamescope
  - intel-media-driver
  - libavcodec-freeworld
  - mesa-va-drivers-freeworld.x86_64
  - mesa-va-drivers-freeworld.i686
  - steam-devices
  - vulkan-loader.i686
  - mesa-vulkan-drivers.i686
  - libglvnd-glx.i686
  - libglvnd-opengl.i686
  - libX11.i686
  - libXext.i686
  - libXrender.i686
  - libXdamage.i686
  - libXfixes.i686
  - libXxf86vm.i686
  - libXrandr.i686
  - libXcomposite.i686
  - libXcursor.i686
  - libXi.i686
  - libXinerama.i686

  # virt-manager.txt
  - qemu
  - virt-manager
  - libvirt
  - dnsmasq
  - ebtables
  - iptables-nft

  # wayland.txt
  - foot
  - ghostty
  - kitty
  - wezterm
  - niri
  - qt5-qtwayland
  - qt6-qtwayland
  - xwayland-satellite
  - jq
  - rofi
  - mako
  - waybar
  - hyprpaper
  - xdg-desktop-portal
  - xdg-desktop-portal-gnome
  - xdg-desktop-portal-gtk
  - socat
  - swaybg
  - grim
  - slurp
  - wl-clipboard
  - wf-recorder
  - satty
  - hyprlock
  - swayidle
  - wlogout
  - cliphist
  - gammastep
  - wlsunset
  - brightnessctl
  - libnotify
  - wlr-randr
  - blueman
  - playerctl
  - pamixer
  - kanshi
  - wayscriber
  - hyprpicker

flatpaks:
  - app.zen_browser.zen
  - com.discordapp.Discord
  - com.slack.Slack
  - md.obsidian.Obsidian
  - org.fedoraproject.MediaWriter
  - com.termius.Termius
  - dev.bragefuglseth.Keypunch
  - com.github.IsmaelMartinez.teams_for_linux
  - net.davidotek.pupgui2
  - org.localsend.localsend_app


